markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github:
author:
email:
name:
url:
domain:
all_categories: [
["c&cpp", "c&cpp","/posts/c&cpp.html"], 
["python", "python","/posts/python.html"],
["variety_store", "杂货铺","/posts/variety_store.html"], 
["reading_notes", "札记","/posts/reading_notes.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: Asia/Shanghai

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
