markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github:
author:
email:
name:
url:
domain:
all_categories: [
["Program", "Program","/posts/program.html"],
["English", "English","/posts/english.html"],
["Kit", "Kit","/posts/kit.html"],
["Notes", "Notes","/posts/notes.html"],
["About", "About","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: Asia/Shanghai

collections:
  docs:
    output: true

plugins:
 - jekyll-paginate
