markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github:
author:
email:
name:
url:
domain:
all_categories: [
["c", "c","/posts/c.html"], 
["python", "python","/posts/python.html"],
["kit", "杂货铺","/posts/kit.html"], 
["note", "札记","/posts/note.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: Asia/Shanghai

collections:
  docs:
    output: true

plugins:
 - jekyll-paginate
